### PR TITLE
Clickable link for faulthandler file

### PR DESCRIPTION
**Pull request by jsbain**
I got sick of the steps to open the last faulthandler file.  This creates a link, that opens in a browser tab.

### CODE REVIEW

**Comment by dgelessus** [comment]
Thanks for the suggestion! I've implemented a modified version of your PR in 10184024d6df98489e99903d18c194cecce8c5fd. It opens the log file in Pythonista itself via the URL scheme, instead of Safari. This should be quicker than launching Safari and doesn't require any app switching. This is based on [this code](https://github.com/dgelessus/pythonista_startup/blob/master/customize_sys_hooks.py#L58) in `customize_sys_hooks.py`, which makes file names in tracebacks tappable links.

**Comment by dgelessus** [comment]
Oh, I just noticed that `file://` links in the console open in Pythonista's built-in browser and not Safari. I didn't realize that before, which is why I made the `pythonista://`-based version instead. My apologies, I didn't mean that as an excuse to not merge your PR.

Now I'm not sure which version is better - the `file://` version goes into a separate tab instead of replacing the current editor tab, but the `pythonista://` version uses the proper editor. Thoughts?

**Comment by jsbain** [comment]
My initial though was I wanted it in the editor, but I was a tad lazy, and file:// was the first thing I tried.

One added benefit of the internal webbrowser is that the logs don't clutter up editor tabs. 
I have found that when crashing pythonista a lot, editor tabs dont always stay closed.

**Comment by dgelessus** [comment]
True, Pythonista saves the open editor tabs before you run the script (I think), so the fault log will stay open if you don't close it by hand. In that case the `file://` version is probably better, because then you don't need to open and close any tabs manually. I'll change that back later when I'm at my iPad again.

**Comment by dgelessus** [comment]
Okay, I changed it back to `file://` in 061b53ec8cae2ca95f3eca1528ab60054ead64b9. Thanks again for the suggestion!

**Pull request closed without merging**
